### PR TITLE
2024-10-11-fix-rollback_session

### PR DESCRIPTION
**Pull request by sjib**
add missing function rollback_session

Should fix https://github.com/QGEP/QGEP/issues/873

### CODE REVIEW

**Comment by sjib** [comment]
@ponceta Does this look like fixing the problem?

Could we eliminate the error messages in this block of `commit_session`?
```

        try:
            self.session.commit()
        except Exception as e:
            self.session.rollback_session()
            iface.messageBar().pushMessage("Error", f"An error occurred: {e}", level=Qgis.Warning)
            iface.messageBar().pushMessage("Error", "Import was canceled", level=Qgis.Warning)
        finally:
            self.session.close()
```

Or better keep them there and only do 

```
    def rollback_session(self):
        self.session.rollback()
```

and not messages, as they are a kind of duplicates?

Thanks for reviewing

**Comment by ponceta** [comment]
This would be better reviewed by @domi4484 but IMHO it should be best to add rollback messages directly in the rollback function.

**Comment by ponceta** [comment]
I think you have to use the function you defined and not `self.session.rollback_session()`
 
        except Exception as e:
            self.rollback_session()
            iface.messageBar().pushMessage("Error", f"An error occurred: {e}", level=Qgis.Warning)
            iface.messageBar().pushMessage("Error", "Import was canceled", level=Qgis.Warning)

**Comment by sjib** [comment]
@ponceta better now?

**Review by ponceta — APPROVED** [review]

**Pull request merged**
