### PR TITLE
correct rohrprofil_geometrie.position to aposition

### PR DESCRIPTION
**Pull request by sjib**
Should solve https://github.com/QGEP/QGEP/issues/854

### CODE REVIEW

**Comment by sjib** [comment]
similar exceptions:

- [x] abwasserbauwerk.astatus
- [x] erhaltungsereignis.astatus
- [x] hydr_kennwerte.astatus

@urskaufmann Are there others - just to document this here.

@urskaufmann Can you manually adapt that change in your installation and check if it works?

**Comment by urskaufmann** [comment]
others are:
organisation.auid
table zone is azone

**Review by urskaufmann — APPROVED** [review]
Works!! Thanks Stefan. Takes 83 min to export 62k networkelements, 6k catchment area and 5k maintenance_events. Without labels.

**Comment by sjib** [comment]
@ponceta Ready to be merged!

**Pull request merged**
