### PR TITLE
Upgrade ili tools to 5.0.1

### PR DESCRIPTION
**Pull request by domi4484**

### CODE REVIEW

**Comment by sjib** [comment]
Should solve also https://github.com/QGEP/QGEP/issues/862

**Comment by ponceta** [comment]
https://github.com/QGEP/QGEP/issues/880#issuecomment-2421785352 @domi4484 do you know why are t_basket issues not logged here?

**Comment by domi4484** [comment]
> why are t_basket issues not logged here?

No but that's quite interesting. Maybe can help me understand how to get rid of the warnings

**Comment by domi4484** [comment]
Replaced by #180 (better to separate the basket logic from the ili dist upgrade to debug easier)
And ili dist upgrade is already part of #138

**Pull request closed without merging**
