### PR TITLE
Upgrade ili binaries distribution

### PR DESCRIPTION
**Pull request by ponceta**
Upgrade ili2pg and ilivalidator

### CODE REVIEW

**Comment by sjib** [comment]
`Model VSA_KEK_2019_LV95 requires column T_basket
Traceback (most recent call last):
  File "/home/runner/work/qgepqwat2ili/qgepqwat2ili/qgepqwat2ili/utils/various.py", line 50, in exec_
    proc = subprocess.run(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '"java" -jar "/home/runner/work/qgepqwat2ili/qgepqwat2ili/qgepqwat2ili/bin/ili2pg-5.1.0-bindist/ili2pg-5.1.0.jar" --schemaimport --dbhost "127.0.0.1" --dbport "5432" --dbusr "postgres" --dbpwd "postgres" --dbdatabase "qgep_prod" --dbschema pg2ili_abwasser --setupPgExt --createGeomIdx --createFk --createFkIdx --createTidCol --importTid --noSmartMapping --defaultSrsCode 2056 --log "/tmp/qgepqwat2ili/240426132109.ilicreate.log" --nameLang de /home/runner/work/qgepqwat2ili/qgepqwat2ili/qgepqwat2ili/ili/VSA_KEK_2019_2_d_LV95-20210120.ili' returned non-zero exit status 1.`

Looks like we have to adapt KEK Import with that change

**Comment by sjib** [comment]
@ponceta I just tested this pullrequest with the new binaries by copying them manually. It does not change anything but still uses the binaries of the ModelBaker version installed. If I do not have ModelBaker installed there is an Error that it is not installed. 

A (hacky) work around is to manually also change the ili2db library version in the QGISModelBaker directory of the QGIS profile used - when I change the ili2db files in the `QGIS\QGIS3\profiles\default\python\plugins\QgisModelBaker\libili2db\bin\ili2pg-4.5.0` folder (keeping the name of the folder and renaming ili2pg-5.1.0 to ili2pg-4.5.0 )  it seems to work (thanks @DflGruBoe for helping me with this).

I have `[QGISModelBaker 6.5.2 installed](https://github.com/opengisch/QgisModelBaker/releases/tag/v6.5.2)` - the last release before it changes to the new architecture with the separeate modelbaker library

So we should:

- [ ] Find out why we still have the need of a ModelBaker installation - and remove it (where in the plugin code do we have that dependency?)
- [ ] Make sure the new ili2db binaries in the qgepplugin folder are used instead

**Comment by sjib** [comment]
Basket handling in ModelBaker see https://opengisch.github.io/QgisModelBaker/background_info/basket_handling/

**Comment by sjib** [comment]
Here is the adapted ModelBaker6.5.2modqgep.zip that has ili2pg 5.1.0 instead of 4.5.0 (as the SCRUM bug was fixed there)

20240802_modelbaker_with_newer_ili2pg_510_instead_450
[Uploading QgisModelBaker6.5.2modqgep.zip…]()

**Comment by sjib** [comment]
[QgisModelBaker6.5.2modqgep.zip](https://github.com/user-attachments/files/16472430/QgisModelBaker6.5.2modqgep.zip)

**Comment by sjib** [comment]
[QgisModelBaker6.5.99modforqgep.zip](https://github.com/user-attachments/files/16472549/QgisModelBaker6.5.99modforqgep.zip)

**Comment by sjib** [comment]
Works with SIA405 Abwasser and VSA-DSS, but creates new problem with VSA-KEK:              `Model VSA_KEK_2019_LV95 requires column T_basket `

**Comment by sjib** [comment]
Does https://github.com/QGEP/qgepqwat2ili/milestone/6 solves this also? @ponceta please coordinate!

**Comment by ponceta** [comment]
Superseded by https://github.com/QGEP/qgepqwat2ili/pull/181

**Pull request closed without merging**
