### PR TITLE
omit empty pg connection settings

### PR DESCRIPTION
**Pull request by olivierdalang**
This improves the way postgres connection settings are generated, to omit empty parameters both in psycopg connections and ili2db CLI.
Hopefully fixes https://github.com/QGEP/QGEP/issues/725

### CODE REVIEW

**Comment by sjib** [comment]
@olivierdalang I now get errors on unittest that have not been before:

` ........................................................................Service `pg_qgep` not found in /home/runner/.pg_service.conf.
Service `pg_qgep` not found in /home/runner/.pg_service.conf.

...usage: python -m unittest [-h] {qgep,qwat,tpl,setupdb} ...
python -m unittest: error: unrecognized arguments: `

https://github.com/QGEP/qgepqwat2ili/actions/runs/3893942420/jobs/6647230294#step:5:2707

**Comment by olivierdalang** [comment]
@sjib is your comment about this PR, or did you intend to post on #84 ?

**Comment by sjib** [comment]
> @sjib is your comment about this PR, or did you intend to post on https://github.com/QGEP/qgepqwat2ili/pull/84 ?

Yes, sorry for the noise.

**Comment by sjib** [comment]
Does this also solves https://github.com/QGEP/qgepqwat2ili/issues/76

**Comment by olivierdalang** [comment]
Yes I think so

**Comment by ponceta** [comment]
Is this ready to merge?

**Comment by sjib** [comment]
I still get the same error when I have no password in pg_conf
`[pg_qgep_swmm3_test]
host=localhost
port=5432
dbname=qgep_swmm3_test
user=postgres
`
I have to add manually when opening the project:

login_missing_password_pg_conf_open_project


And then I get the error when running INTERLIS import:
a) with the latest plugin 1.5.6-b9

Ein Fehler trat bei der Ausführung von Python-Code auf: 

psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 199, in action_do_export
    create_ili_schema(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 15, in create_ili_schema
    connection = psycopg2.connect(
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied



Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.28.2-Firenze Firenze, b47e00ba601 

Python-Pfad:
C:/PROGRA~1/QGIS 3.28.2/apps/qgis/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python/plugins
C:/PROGRA~1/QGIS 3.28.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.2\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib
C:\Program Files\QGIS 3.28.2\bin
C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.28.2\apps\Python39
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python
C:/Daten/TEKSI/4_Feature_requests/SWMM/dss2swmm/20230123_testing_v3
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\teksi_standard/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..
.

b) and the latest master:

An error has occurred while executing Python code: 

psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied 
Traceback (most recent call last):
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\__init__.py", line 194, in action_do_export
    create_ili_schema(
  File "C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\utils\ili2db.py", line 13, in create_ili_schema
    connection = psycopg2.connect(get_pgconf_as_psycopg2_dsn())
  File "C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: fe_sendauth: no password supplied



Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.2-Firenze Firenze, b47e00ba601 

Python Path:
C:/PROGRA~1/QGIS 3.28.2/apps/qgis/./python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.28.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.2\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib
C:\Program Files\QGIS 3.28.2\bin
C:\Users\Stefan\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS 3.28.2\apps\Python39
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Daten/TEKSI/4_Feature_requests/SWMM/dss2swmm/20230123_testing_v3
C:\Users/Stefan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgepplugin\qgepqwat2ili\qgepqwat2ili\gui\..\..

@urskaufmann Not sure if this is your case or if it differs https://github.com/QGEP/QGEP/issues/725
.

**Comment by urskaufmann** [comment]
Not quite sure what you mean with this question. I tried now INTERLIS Export with QGIS 3.28.2 and qgep 1.56-b9 and I had no more problem with the password - it worked without postgres-password...
One difference is: when opening the project we have never to give a password (password is taken from windows-login)

**Pull request merged**
